kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: frontend
  image: node:slim
  commands:
  - npm version

- name: python
  image: python:rc-alpine
  commands:
  - python -V
