kind: pipeline
name: default

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test -short

node:
  instance: "failure-domain.beta.kubernetes.io/region: eu-central-1"
