kind: pipeline
name: default
insecure: true

platform:
  os: linux
  arch: amd64

steps:
steps:
- name: frontend
  image: node
  commands:
  - npm install
  - npm test

steps:
- name: frontend2
  image: node
  commands:
  - npm install
  - npm test
