version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    environment:
      TEST: true

    steps:
      - checkout
      - include:
          - # require the branch name to be master (note for PRs this is the base branch name)
            if: branch = master
            env: FOO=foo
      - run:
          name: current branch
          command: |
            printenv | grep foo



workflows:
  version: 2

  CICD:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - develop
                - /release.*/
                - master
