version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    environment:
      TEST: true

    steps:
      - checkout
      - run:
          name: checkout to the branch
          command: |
            git checkout $CIRCLE_BRANCH
      - run:
          name: current branch
          command: |
            echo $(env | grep foo)
            git branch
          branches:
            only:
              - master
              - develop



workflows:
  version: 2

  CICD:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - develop
                - /release-.*/
                - master
