version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    environment:
      TEST: true

    steps:
      - checkout
      - run:
          name: current branch
          command: |
            printenv | grep foo
          branches:
            only:
              - master



workflows:
  version: 2

  CICD:
    jobs:
      - build_and_test:
          filters:
            branches:
              only:
                - develop
                - /release.*/
                - master
