version: 2
jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.6.5

    working_directory: ~/repo

    environment:
      TEST: true

    steps:
      - checkout $TRAVIS_BRANCH
      - run:
          name: current branch
          command: |
            git branch


            kubectl set image -f ~/repo/k8s-resources/customer_transactions/trx-listener-media-deploy.yaml trx-customer-transactions-listener-media=$AWS_ECR_REGISTRY_CUST_TRX:$CIRCLE_PREVIOUS_BUILD_NUM
workflows:
  version: 2

  CICD:
    jobs:
      - build_and_test:
